### ISSUE TITLE
Don't require Node 8

### ISSUE THREAD

**Issue by paulfalgout** [cypress-io/cypress-webpack-preprocessor#16]
Node 6 should work fine with this plugin and it is LTS for another year.  Yarn forces the engine to match.  Forcing the engine to version 8 means that you can't use cypress with the preprocessor and webpack 4 unless you're on Node 8.

This seems unnecessary.

**Comment by chrisbreiding** [comment]
Thanks for pointing that out. I'm starting to think requiring a version of Node at all doesn't really make sense at all since plugins run in the Node that ships with Cypress. Probably just need a note in the readme to that effect. The bigger concern is that if you require your own code into the pluginsFile, it needs to be compatible with Cypress's Node version.

**Comment by chrisbreiding** [comment]
Removed the node version requirement in `2.0.1`.
