### ISSUE TITLE
Webpack is bundled

### ISSUE THREAD

**Issue by sarink** [cypress-io/cypress-webpack-preprocessor#21]
Why is webpack bundled within this plugin?

My app is using a different version of webpack, and the configs are incompatible. I've _finally_ been able to move forward by rewriting my config and using a fragile combination of different loaders than I currently use to bundle my app, locked at specific versions that seem to work with this plugin (specifically, `awesome-typescript-loader` blows up, but `ts-loader@3.2.0` does not).

Having your app be compiled one way, and having your tests for that app (which imports your source files), be compiled another different way, seems pretty bad.

Why can't I bundle my tests with my own webpack and my own configuration, and simply supply the output to cypress?

**Comment by sarink** [comment]
Does it matter? :-P Anything that's different from whatever I get when I `npm install` on this https://github.com/cypress-io/cypress-webpack-preprocessor/blob/master/package.json#L65 has the potential to cause this issue, right?

**Comment by chrisbreiding** [comment]
https://github.com/cypress-io/cypress-webpack-preprocessor#compatibility

**Comment by sarink** [comment]
I've seen that :), but your `package.json` isn't an explicit version. Even within webpack versions there are subtle differences.

Compiling the app differently for testing just seems bad, so I was wondering if there was a way that this I could simply send cypress the "already bundled output" rather than bundling it itself with this package?

**Comment by chrisbreiding** [comment]
The reason webpack is bundled with this plugin is to make it as easy to use as possible for the majority of users. Also, since it relies on the webpack's programmatic API, the webpack version needs to be under control or it won't be guaranteed to work.

If you'd like to bundle your test code yourself, you can utilize the [preprocessor API](https://docs.cypress.io/api/plugins/preprocessors-api.html) directly to then send the bundled output to cypress. Or it might be easiest to fork this repo and set it to use the webpack version you need.

**Comment by sarink** [comment]
Got it. Thanks!

**Comment by paulfalgout** [comment]
seems like `peerDependency` might solve the "easy to use" for the majority of users issue without duplicating the libraries dependencies for almost everyone.
