### ISSUE TITLE
Headless + Typescript

### ISSUE THREAD

**Issue by mspoulsen** [cypress-io/cypress-webpack-preprocessor#57]
Is Cypress capable of running headlessly if the codebase is Typescript?

**Comment by jennifer-shehane** [comment]
Yes, please refer to https://docs.cypress.io/guides/tooling/typescript-support.html#Transpiling-TypeScript-test-files

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
